Staging
CityOfPhiladelphia/phila.gov pull request #1650
Opened 2022-08-30 21:04 UTC by derrickdso

2022-08-30 21:35 UTC, karissademi requested changes
A couple of comments, mostly around double checking that all the styles are necessary. This is great work!

2022-08-30 21:35 UTC, karissademi commented on wp/wp-content/plugins/phila.gov-customization/public/class-phila-gov-site-wide-alert-rendering.php
> +                    <a class="button" href="https://vote.phila.gov/my-vote-my-way/"><b>MAKE A PLAN TO VOTE</b></a>
We can drop the <b> and the all caps text here. Those are already part of the button styles, so no need to hard code it that way.

2022-08-30 21:35 UTC, karissademi commented on wp/wp-content/plugins/phila.gov-customization/public/class-phila-gov-site-wide-alert-rendering.php
> +                    <a class="button" href="https://vote.phila.gov/my-vote-my-way/"><b>MAKE A PLAN TO VOTE</b></a>
At some point, this link changed and I didn't update the ticket, apologies: https://vote.phila.gov/voting/my-vote-my-way/

2022-08-30 21:35 UTC, karissademi commented on wp/wp-content/themes/phila.gov-theme/css/scss/_alerts.scss
> +  background-color: #f0f0f0;
We can use `background-color: color(ghost-gray)` here. See: https://standards.phila.gov/docs/design/brand-elements/color-palette.html

2022-08-30 21:35 UTC, karissademi commented on wp/wp-content/themes/phila.gov-theme/css/scss/_alerts.scss
> +    color: black;
Can we double check that all these rules are needed? For example, the color, height and text-alignment are all likely already part of button styles. 

Same comment for the float: left on the link. Are we sure that's necessary?

2022-08-31 14:36 UTC, derrickdso commented on wp/wp-content/themes/phila.gov-theme/css/scss/_alerts.scss
> +    color: black;
float left is to left align the whole button on mobile but the extra styles were cleaned up

2022-08-31 16:54 UTC, karissademi approved these changes

2022-08-31 19:46 UTC, merged