Default 2020 modal
CityOfPhiladelphia/phila.gov pull request #1928
Opened 2023-06-28 19:21 UTC by IshKeyes

https://www.wrike.com/open.htm?id=1129623387

2023-06-28 19:22 UTC, IshKeyes commented
Generic modal created for default 2020 template.

2023-07-05 14:40 UTC, derrickdso requested changes
Left comments, lmk if you have questions

2023-07-05 14:40 UTC, derrickdso commented on wp/wp-content/themes/phila.gov-theme/partials/services/content-phila-modal.php
> +    <?php endif ?>
fix the indenting on this file please

2023-07-05 14:40 UTC, derrickdso commented on wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-standard-metaboxes.php
> +        'name'  => 'Clickable link text',
remove commented out fields from this

2023-07-05 14:40 UTC, derrickdso commented on wp/wp-content/themes/phila.gov-theme/partials/services/content-phila-modal.php
> +        <div class="phm-mu"><button class="link" data-open="<?php echo sanitize_title_with_dashes($phila_modal_link_text)?>"><i class="fas fa-info-circle"></i> <?php echo $phila_modal_link_text ?></b
Let's change the cursor to a pointer on hover using css for this modal. This might also need to be applied to the original modal, please confirm.

2023-07-14 17:38 UTC, derrickdso requested changes

2023-07-14 17:38 UTC, derrickdso commented on wp/wp-content/themes/phila.gov-theme/css/scss/_lightbox.scss
> +  cursor: pointer;
Not quite, we want the hover state on the button itself to be the cursor, not the modal content.
![image](https://github.com/CityOfPhiladelphia/phila.gov/assets/16737142/e2d6e94b-18d1-49a0-9d5a-77e1e0c2604a)

2023-07-14 17:59 UTC, derrickdso approved these changes

2023-07-14 18:01 UTC, merged