wysiwyg added
CityOfPhiladelphia/phila.gov pull request #2030
Opened 2023-11-03 13:52 UTC by IshKeyes

https://www.wrike.com/open.htm?id=977135713

2023-11-06 21:50 UTC, derrickdso requested changes

2023-11-06 21:50 UTC, derrickdso commented on wp/wp-content/themes/phila.gov-theme/partials/services/content-topic-page.php
> +      <?php echo rwmb_meta( 'phila_wysiwyg_content' ); ?>
what happens if this field isn't set? Should just the div be impacted or the whole section?

2023-11-10 17:54 UTC, IshKeyes commented
Here are other service pages that you the topic page template that I tested:
http://philagov.local/services/birth-marriage-life-events/marriage-and-divorce/
http://philagov.local/services/birth-marriage-life-events/death-probate-and-inheritances/

2023-11-15 15:02 UTC, derrickdso approved these changes

2023-11-15 15:02 UTC, merged