feat: added blog posts cpt
CityOfPhiladelphia/phila.gov pull request #2072
Opened 2024-01-11 16:02 UTC by RitikaDesai98

2024-01-30 16:47 UTC, derrickdso commented
Standard Blog post - BE

![image](https://github.com/CityOfPhiladelphia/phila.gov/assets/16737142/2df68dec-a630-4b11-85df-62014f032682)
This is showing on blog posts on the new template

2024-01-30 16:47 UTC, derrickdso commented
Standard Blog post - FE
Needs breadcrumbs like this. Breadcrumbs should be exactly the same as old posts.
![image](https://github.com/CityOfPhiladelphia/phila.gov/assets/16737142/fa960ac7-8f8c-4eac-ab0a-e74c3b62cc39)
vs
![image](https://github.com/CityOfPhiladelphia/phila.gov/assets/16737142/fbe23966-31f9-44db-a463-df87403b51c4)

2024-01-30 19:35 UTC, derrickdso commented
Standard Blog post - FE 

Related posts section is missing
![image](https://github.com/CityOfPhiladelphia/phila.gov/assets/16737142/d5968746-0074-4634-94ec-4ada804271d0)

2024-01-30 21:55 UTC, derrickdso commented
wp-admin - enable author field

2024-01-30 22:22 UTC, derrickdso commented
Series page  - FE

Adjust padding on wys content 
https://app.axure.cloud/app/project/g4kyse/preview/7uc3o0
![image](https://github.com/CityOfPhiladelphia/phila.gov/assets/16737142/9d1a65f7-d056-471f-b35c-ac64a9a653ed)

2024-01-30 22:29 UTC, derrickdso commented
Series - FE

Items seem to disappear on mobile
![image](https://github.com/CityOfPhiladelphia/phila.gov/assets/16737142/948c1c46-d84a-44fc-a6d4-819bcc1189cd)

2024-03-22 21:32 UTC, karissademi requested changes
I have a lot of minor comments. Overall this is _great_ work. All of the template improvements you've included are excellent and much needed for clarity and maintenance!

2024-03-22 21:32 UTC, karissademi commented on wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-standard-metaboxes.php
> +            array(
I don't think we have a way to pass "required" to this field, if we do, let's make the field required. If not, let's adjust the standard metabox`phila_metabox_v2_phila_text` to allow for the "required" option.

2024-03-22 21:32 UTC, karissademi commented on wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-standard-metaboxes.php
> +            Phila_Gov_Standard_Metaboxes::phila_timeline_page_selector(),
I never noticed this before, but the `phila_timeline_page_selector` should really only allow 1 item to be selected (right now it's automatically defaulting to the first item). I believe this change can be made to the standard metabox without ill effect, but we should implement that and test it first.

2024-03-22 21:32 UTC, karissademi commented on wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-standard-metaboxes.php
> +                  'name' => 'Description',
Is this meant to be optional? If so, let's add a check on the front-end so we don't get `Notice: Undefined index: phila_image_gallery_description`

2024-03-22 21:32 UTC, karissademi commented on wp/wp-content/themes/phila.gov-theme/js/dev/advanced-posts.js
> +module.exports = $(function () {
This is good, but we need to check when the height of the photo changes from the first image in the slideshow and ensure the controls are sticking to the bottom. They are perfectly placed for the first image, but subsequent ones remember the height of the first image without updating the placement. See screeshot 
<img width="1030" alt="Screenshot 2024-03-22 at 5 10 40 PM" src="https://github.com/CityOfPhiladelphia/phila.gov/assets/479028/cb934847-2bcd-4173-8c5f-2ab333cb79e2">

2024-03-22 21:32 UTC, karissademi commented on wp/wp-content/themes/phila.gov-theme/partials/phila_blog_adv_image_gallery.php
> +            $media_credit = get_post_meta($image['phila_images'][0])['phila_media_credit'][0];
Let's add some checks around these fields to avoid notices when these fields are blank. Should be in place for: $media_credit and $media_caption.

2024-03-22 21:32 UTC, karissademi commented on wp/wp-content/themes/phila.gov-theme/partials/posts/phila-series.php
> +                        <p><?php echo ucfirst($post_type); ?></p>
Is "ucfirst" meant to render the text "blog_post" or something else?
<img width="300" alt="Screenshot 2024-03-22 at 5 22 59 PM" src="https://github.com/CityOfPhiladelphia/phila.gov/assets/479028/1e3a27b8-9f0c-42c5-988f-ff5ea7acb483">

2024-03-22 21:32 UTC, karissademi commented on wp/wp-content/themes/phila.gov-theme/partials/posts/phila-series.php
> +                        <img class = "series-img" src="<?php echo wp_get_attachment_image_src(get_post_thumbnail_id($row), 'thumbnail')[0] ?>">
We need to change  the WordPress Media settings if we're going to use the 'thumbnail'. Right now the size is 150x150 and it's seriously pixelating the image. Let's try it with size "medium" to see if it looks any better and if not, let's chat about options here.

2024-03-22 21:32 UTC, karissademi commented on wp/wp-content/themes/phila.gov-theme/templates/blog_post.php
> +            <?php $image_credit = get_post_meta(get_post_thumbnail_id())['phila_media_credit'][0]; ?>
Add a check for $image_caption and $image_credit since not all images have these fields.

2024-03-22 21:32 UTC, karissademi commented on wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-standard-metaboxes.php
> +              'desc'  => 'Select the number of items from the timeline to display',
This setting is available, but I don't think there is a corresponding limiter on the new timeline stub template.

2024-05-22 14:12 UTC, karissademi commented on wp/wp-content/plugins/phila.gov-customization/admin/meta-boxes/class-phila-gov-standard-metaboxes.php
> +            Phila_Gov_Standard_Metaboxes::phila_timeline_page_selector(),
Will fix in the future, not here

2024-05-22 14:14 UTC, karissademi approved these changes

2024-05-22 14:19 UTC, merged